baseURL = 'http://aa-9000.github.io/'
languageCode = 'en-us'
title = 'Brain dumps and tech notes'
theme = 'hugo-theme-relearn'

[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
themeVariant = "blue"


